### ISSUE TITLE
Fix pending tests and add new tests

### ISSUE THREAD

**Issue by rubydog** [Snowfork/BTRUST-Contracts#9]
Fix pending tests in master and add following tests for GovernorAlpha

* https://github.com/compound-finance/compound-protocol/blob/master/tests/Governance/GovernorAlpha/QueueTest.js
* https://github.com/compound-finance/compound-protocol/blob/master/tests/Governance/GovernorAlpha/StateTest.js

**Comment by musnit** [comment]
Also review code for any skipped tests and fix them
